version: "3"

services:

  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "5005:8080"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
