services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PASSWORD=abc123
      - API_HOST=app
      - API_PORT=8080
    volumes:
      - ./:/workspace
    ports:
      - "5005:8080"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
